    ------  CON DAX  ------

Calendario = 
ADDCOLUMNS(
    CALENDAR(
        
        MIN(Sales[Date]),
        MAX(Sales[Date])),

        "Año", YEAR([Date]),
        "Mes", MONTH([Date]),
        "Trimestre", QUARTER([Date]),
        "Día", DAY([Date]),
        "Dia de la semana", WEEKDAY([Date]),
        "Nombre del mes", FORMAT([Date],"MMMM"),
        "Trimestre-letras", 
            SWITCH(
                QUARTER([Date]), 
                1, "Primero",
                2, "Segundo",
                3, "Tercero",
                4, "Cuarto",
                 "Fallo en trimestre")
)


   ------ CON M  ------

let
    // Obtener el mínimo y máximo de la tabla Sales (ya debe estar cargada en Power Query)
    MinFecha = List.Min(Sales[Date]),
    MaxFecha = List.Max(Sales[Date]),

    // Crear una lista de fechas desde Min hasta Max
    Dias = Duration.Days(MaxFecha - MinFecha),
    Fechas = List.Dates(MinFecha, Dias + 1, #duration(1, 0, 0, 0)),

    // Convertir la lista a tabla
    TablaFechas = Table.FromList(Fechas, Splitter.SplitByNothing(), {"Date"}),

    // Agregar columnas adicionales
    TipoFecha = Table.TransformColumnTypes(TablaFechas, {{"Date", type date}}),
    ConAño = Table.AddColumn(TipoFecha, "Año", each Date.Year([Date]), Int64.Type),
    ConMes = Table.AddColumn(ConAño, "Mes", each Date.Month([Date]), Int64.Type),
    ConTrimestre = Table.AddColumn(ConMes, "Trimestre", each Date.QuarterOfYear([Date]), Int64.Type),
    ConDia = Table.AddColumn(ConTrimestre, "Día", each Date.Day([Date]), Int64.Type),
    ConDiaSemana = Table.AddColumn(ConDia, "Día de la semana", each Date.DayOfWeek([Date]) + 1, Int64.Type),
    ConNombreMes = Table.AddColumn(ConDiaSemana, "Nombre del mes", each Date.ToText([Date], "MMMM"), type text),
    ConTrimestreLetra = Table.AddColumn(ConNombreMes, "Trimestre-letras", each 
        if Date.QuarterOfYear([Date]) = 1 then "Primero" 
        else if Date.QuarterOfYear([Date]) = 2 then "Segundo"
        else if Date.QuarterOfYear([Date]) = 3 then "Tercero"
        else if Date.QuarterOfYear([Date]) = 4 then "Cuarto"
        else "Fallo en trimestre", type text)
in
    ConTrimestreLetra
